stages:
  - build
  
pack:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}
    - apk add git
  script:
    # decide which image tags to build and push
    - |
        tags=":${CI_COMMIT_REF_SLUG} :${CI_COMMIT_REF_SLUG}-$(git describe --dirty --always)"
        if [[ "${CI_COMMIT_REF_NAME}" == "${CI_DEFAULT_BRANCH}" ]]; then
          tags="${tags} :latest"
        fi
        if [[ -n "${CI_COMMIT_TAG}" ]]; then
          tags="${tags} :${CI_COMMIT_TAG}"
        fi
        echo "Running on branch '${CI_COMMIT_BRANCH}': tags = [${tags}]"
    # build and push image with all defined tags
    - |
        for tag in ${tags}; do
          docker build -t ${CI_REGISTRY_IMAGE}${tag} --file=build/image/Dockerfile .
          docker push ${CI_REGISTRY_IMAGE}${tag}
        done
    - |
        for tag in ${tags}; do
          docker build -t ${CI_REGISTRY_IMAGE}${tag}-profiling --file=build/image/Dockerfile .
          docker push ${CI_REGISTRY_IMAGE}${tag}-profiling
        done


