/* automatically generated by rust-bindgen 0.69.1 */
#![allow(non_camel_case_types)]

pub type __u64 = ::aya_bpf::cty::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pt_regs {
    pub r15: ::aya_bpf::cty::c_ulong,
    pub r14: ::aya_bpf::cty::c_ulong,
    pub r13: ::aya_bpf::cty::c_ulong,
    pub r12: ::aya_bpf::cty::c_ulong,
    pub bp: ::aya_bpf::cty::c_ulong,
    pub bx: ::aya_bpf::cty::c_ulong,
    pub r11: ::aya_bpf::cty::c_ulong,
    pub r10: ::aya_bpf::cty::c_ulong,
    pub r9: ::aya_bpf::cty::c_ulong,
    pub r8: ::aya_bpf::cty::c_ulong,
    pub ax: ::aya_bpf::cty::c_ulong,
    pub cx: ::aya_bpf::cty::c_ulong,
    pub dx: ::aya_bpf::cty::c_ulong,
    pub si: ::aya_bpf::cty::c_ulong,
    pub di: ::aya_bpf::cty::c_ulong,
    pub orig_ax: ::aya_bpf::cty::c_ulong,
    pub ip: ::aya_bpf::cty::c_ulong,
    pub cs: ::aya_bpf::cty::c_ulong,
    pub flags: ::aya_bpf::cty::c_ulong,
    pub sp: ::aya_bpf::cty::c_ulong,
    pub ss: ::aya_bpf::cty::c_ulong,
}
pub type bpf_user_pt_regs_t = pt_regs;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bpf_perf_event_data {
    pub regs: bpf_user_pt_regs_t,
    pub sample_period: __u64,
    pub addr: __u64,
}

